todolist/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

# 'auth' 블루프린트 생성
auth = Blueprint('auth', __name__)

# 로그인 뷰 및 로직
@auth.route('/login', methods=['GET', 'POST'])
def login():
    # 이미 인증된 사용자인 경우 메인 화면으로 리디렉션
    if current_user.is_authenticated:
        return redirect(url_for('views.task_list'))

    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        # 입력한 이메일에 해당하는 사용자 정보 조회
        user = User.query.filter_by(email=email).first()

        if user:
            # 입력한 비밀번호와 저장된 비밀번호를 비교하여 인증
            if check_password_hash(user.password, password):
                flash("Logged in Successfully!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.task_list'))
            else:
                flash("Incorrect password, try again", category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

# 로그아웃 뷰 및 로직
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged Out!', category='success')
    return redirect(url_for('auth.login'))

# 회원가입 뷰 및 로직
@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    # 이미 인증된 사용자인 경우 메인 화면으로 리디렉션
    if current_user.is_authenticated:
        return redirect(url_for('views.task_list'))

    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        # 입력한 이메일에 해당하는 사용자 정보 조회
        user = User.query.filter_by(email=email).first()

        if user:
            flash("Email already exists.", category='error')
        elif len(first_name) < 2:
            flash("First name must be greater than 1 characters.", category='error')
        elif password1 != password2:
            flash("Passwords don't match.", category='error')
        elif len(password1) < 4:
            flash("Password must be at least 4 characters long.", category='error')
        else:
            # 새로운 사용자 생성 및 데이터베이스에 저장
            new_user = User(email=email, password=generate_password_hash(password1, method='sha256'), first_name=first_name)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category='success')
            return redirect(url_for('views.task_list'))

    return render_template("sign_up.html", user=current_user)

todolist/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required
from .models import Task
from . import db
import random


views = Blueprint('views', __name__)
quotes = [
    "\"가장 바쁜 사람이 가장 많은 시간을 갖는다\"",
    "\"미래를 예측하는 최선의 방법은 미래를 창조하는 것이다\"",
    "\"시간과 정성을 들이지 않고 얻을 수 있는 결실은 없다\"",
    "\"승자는 시간을 관리하며 살고 패자는 시간에 끌려 산다\"",
    "\"당신은 지체할 수도 있지만 시간은 그러지 않을 것이다\"",
    "\"시간은 우리를 변화시키지 않는다. 시간은 단지 우리를 펼쳐 보일 뿐이다\"",
    "\"지붕은 햇빛이 밝을 때 수리해야 한다\"",
    "\"오늘 회피한다고 내일의 책임에서 벗어날 수는 없다\"",
    "\"낭비한 시간에 대한 후회는 더 큰 시간 낭비이다\"",
    "\"10분 뒤와 10년 후를 동시에 생각하라\"",
    
]




@views.route('/task-create', methods=['GET', 'POST'])
@login_required
def task_form():

    if request.method == "POST":
        title = request.form.get('title')
        description = request.form.get('description')
        complete = request.form.get('complete')

        if complete:
            complete = True

        new_task = Task(title=title, description=description, complete=complete, user_id=current_user.id)
        db.session.add(new_task)
        db.session.commit()
        flash("Task created!", category='success')
        return redirect(url_for('views.task_list'))

    return render_template("task_form.html", user=current_user)



    return render_template("task_form2.html", user=current_user)

@views.route('/task-delete/<int:id>', methods=['GET', 'POST'])
@login_required
def task_delete(id):
    task = Task.query.filter_by(id=id).first()
    if request.method == "POST":
        db.session.delete(task)
        db.session.commit()
        flash("Task Deleted!", category='success')
        return redirect(url_for("views.task_list"))

    return render_template("task_confirm_delete.html", task=task)


@views.route('/task-update/<int:id>', methods=['GET', 'POST'])
@login_required
def task_update(id):
    task = Task.query.filter_by(id=id).first()
    if request.method == "POST":
        task.title = request.form.get('title')
        task.description = request.form.get('description')
        complete = request.form.get('complete')

        if complete:
            complete = True
        else:
            complete = False

        task.complete = complete
        db.session.commit()
        flash("Task Updated!", category='success')
        return redirect(url_for("views.task_list"))

    return render_template("task_update.html", task=task)


@views.route('/task_list', methods=['GET', 'POST'])
@login_required
def task_list():
    count = Task.query.filter_by(user_id=current_user.id, complete=False).count()
    plural = True if count > 1 else False
    tasks = current_user.tasks
    search_input = ''
    random_quote = random.choice(quotes)

    if request.method == "POST":
        search = request.form.get('search-area')
        search_input = search
        result = Task.query.filter(Task.title.like(f'%{search}%'), Task.user_id == current_user.id).all()
        tasks = result
        
    return render_template("task_list.html", user=current_user, plural=plural, count=count, tasks=tasks, random_quote=random_quote, search_input=search_input)

@views.route('/task_list1', methods=['GET', 'POST'])
@login_required
def task_list1():
    count = Task.query.filter_by(user_id=current_user.id, complete=False).count()
    plural = True if count > 1 else False
    tasks = current_user.tasks
    search_input = ''
    random_quote = random.choice(quotes)

    if request.method == "POST":
        search = request.form.get('search-area')
        search_input = search
        result = Task.query.filter(Task.title.like(f'%{search}%'), Task.user_id == current_user.id).all()
        tasks = result
        
    return render_template("task_list1.html", user=current_user, plural=plural, count=count, tasks=tasks, random_quote=random_quote, search_input=search_input)
@views.route('/task_list2', methods=['GET', 'POST'])
@login_required
def task_list2():
    count = Task.query.filter_by(user_id=current_user.id, complete=False).count()
    plural = True if count > 1 else False
    tasks = current_user.tasks
    search_input = ''
    random_quote = random.choice(quotes)

    if request.method == "POST":
        search = request.form.get('search-area')
        search_input = search
        result = Task.query.filter(Task.title.like(f'%{search}%'), Task.user_id == current_user.id).all()
        tasks = result
        
    return render_template("task_list2.html", user=current_user, plural=plural, count=count, tasks=tasks, random_quote=random_quote, search_input=search_input)

todolist/templates/login.html
{% extends 'main.html' %}
{% block extra_styles %}
    <style>
        /* 네비게이션 메뉴 숨기기 */
        #nav {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="header-bar">
        <h1>오늘, 내일</h1>
    </div>

    <div class="card-body">
        <form action="" method="post">
            <label>ID:</label>
            <input type="email" name="email">

            <label>Password:</label>
            <input type="password" name="password">

            <input style="margin-top: 10px;" class="button" type="submit" value="Login">
        </form>
        <p>Don't Have An Account? <a href="{{ url_for('auth.sign_up') }}">Register</a></p>
    </div>

{% endblock %}

todolist/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To Do List</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    {% block extra_styles %}{% endblock %}
    <style>
        ul {
            list-style: none;
            padding: 0;
        }
        li {
            display: inline-block;
            margin-right: 10px;
        }
    </style>
</head>
<body>

{% block header %}
    <section id="header">
        <!-- 네비게이션 메뉴 -->
         <nav id="nav">
            <ul>
                <li><a href="{{ url_for('views.task_list') }}" class="button" >오늘의 할 일</a></li>
                <li><a href="{{ url_for('views.task_list1') }}"class="button">이번 주의 할 일</a></li>
                <li><a href="{{ url_for('views.task_list2') }}"class="button">이번 달의 할 일</a></li>
                
            </ul>
        </nav>
    </section>

    <script>
        // 버튼 클릭 이벤트 핸들러
        function handleClick(event) {
            var buttonId = event.target.id;
            var destination = '';

            // 버튼에 따라 이동할 경로 설정
            if (buttonId === 'button1') {
                destination = 'main.html';
            } else if (buttonId === 'button2') {
                destination = 'main1.html';
            } else if (buttonId === 'button3') {
                destination = 'main2.html';
            }

            // 경로로 이동
            window.location.href = destination;
        }

        // 버튼 클릭 이벤트 등록
        var button1 = document.getElementById('button1');
        var button2 = document.getElementById('button2');
        var button3 = document.getElementById('button3');

        button1.addEventListener('click', handleClick);
        button2.addEventListener('click', handleClick);
        button3.addEventListener('click', handleClick);
    </script>
{% endblock %}

{% block content %}
{% endblock %}

</body>
</html>

todolist/templates/sign_up.html
{% extends 'main.html' %}
{% block extra_styles %}
    <style>
        /* 네비게이션 메뉴 숨기기 */
        #nav {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">

        <label>Firstname</label>
        <input type="text" name="firstName">

        <label>Email Address</label>
        <input type="email" name="email">


        <label>Password</label>
        <input type="password" name="password1">

        <label>Confirm Password</label>
        <input type="password" name="password2">

        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login</a></p>
</div>

{% endblock %}

todolist/templates/task_confirm_delete.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{{ url_for('views.task_list') }}">&#8593;Go Back</a>
</div>

<div class="card-body">
    <form action="" method="post">
        <p>Are You sure you want to delete this task? "{{task}}"</p>
        <input class="button" type="submit" value="delete">
    </form>
</div>

{% endblock %}

todolist/templates/task_form.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{{ url_for('views.task_list') }}">&#8592; Back</a>
</div>

  <div class="card-body">
      <form action="" method="post">

          <label>Title</label>
          <input type="text" name="title">

          <label>Description</label>
          <textarea rows="5" name="description"></textarea>

          <label>Complete<input type="checkbox" name="complete"></label>

          <input style="margin-top:10px;" class="button" type="submit" value="Submit">
      </form>
  </div>

{% endblock %}

todolist/templates/task_list.html
{% extends 'main.html' %}

{% block content %}
{% if current_user.is_authenticated %}
<div class="header-bar">
    <div>
        <h1>"{{ current_user.first_name|title }}" 님의 오늘 할 일 !!<p>{{ random_quote }}</h1>
        <h3 style="margin:0"> 오늘 해야 할 일이 <i>{{ count }}</i>가지 남았어요!
            
        </h3>
    </div>

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.logout') }}">Logout</a>
    {% else %}
    <a href="#">Login</a>
    {% endif %}
</div>

<div id="search-add-wrapper">
    <form action="" method="post" style="margin-top: 20px; display: flex;">
        <input type="text" name="search-area" value="{{ search_input }}">
        <input class="button" type="submit" value="Search">
        
    </form>
    <div style="text-align: right;">
        <a id="add-link" href="{{ url_for('views.task_form') }}" style="margin-right: 50px;" >&#x2b; 할일 추가</a>
        <a id="add-link1" href="{{ url_for('views.task_form') }}" style="margin-right: 100px;" >&#x2b;일기 쓰기</a>
   </div>
    
</div>


<div class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper">
        {% if task.complete %}
        <div class="task-title">
            <div class="task-complete-icon"></div>
            <i><s><a href="{{ url_for('views.task_update', id=task.id) }}">{{ task.title }}<p></a></s></i>
        </div>
        {% else %}
        <div class="task-title">
            <div class="task-incomplete-icon"></div>
            <a href="{{ url_for('views.task_update', id=task.id) }}">{{ task.title }}</p></a>

            
        </div>
        {% endif %}
        {% if task.description|length >= 10 %}
        <div class="task-description">
            <h3>{{ task.title }}</h3>
            <p>{{ task.description }}</p>  <!-- description 출력 -->
        </div>
        {% endif %}
        <div class="delete-button" >
            <a href="{{ url_for('views.task_delete', id=task.id) }}">X</a>
        </div>
    </div>
    {% else %}
    <h3 style="margin-left:10px;">해야 할 일이 없어요!</h3>
    {% endfor %}
</div>


{% endif %}

{% endblock %}

todolist/templates/task_list1.html
{% extends 'main.html' %}

{% block content %}
{% if current_user.is_authenticated %}
<div class="header-bar">
        <div>
            <h1>"{{current_user.first_name|title}}"  님의 이번 주의 할 일<p>{{ random_quote }}</h1>
            <h3 style="margin:0">오늘 해야 할 일이 <i>{{ count }}</i>가지 남았어요!
             
            </h3>
        </div>

        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
        <a href="#">Login</a>
        {% endif %}
    </div>

    <div id="search-add-wrapper">
        <form action="" method="post" style="margin-top: 20px; display: flex;">
            <input type="text" name="search-area" value="{{ search_input }}">
            <input class="button" type="submit" value="Search">
            
        </form>
        <div style="text-align: right;">
            <a id="add-link" href="{{ url_for('views.task_form') }}" style="margin-right: 50px;" >&#x2b; 할일 추가</a>
            <a id="add-link1" href="{{ url_for('views.task_form') }}" style="margin-right: 100px;" >&#x2b;일기 쓰기</a>
       </div>
        
    </div>


    <div class="task-items-wrapper">
        {% for task in tasks %}
            <div class="task-wrapper">
                {% if task.complete %}
                    <div class="task-title">
                        <div class="task-complete-icon"></div>
                        <i><s><a href="{{ url_for('views.task_update', id=task.id) }}">{{task.title}}</a></s></i>
                    </div>
                <a class="delete-link" href="{{ url_for('views.task_delete', id=task.id) }}">&#215;</a>
                {% else %}
                    <div class="task-title">
                        <div class="task-incomplete-icon"></div>
                        <a href="{{ url_for('views.task_update', id=task.id) }}">{{task.title}}</a>
                    </div>
                <a class="delete-link" href="{{ url_for('views.task_delete', id=task.id) }}">&#215;</a>
                {% endif %}

            </div>
        {% else %}
        <h3 style="margin-left:10px;">해야 할 일이 없어요!</h3>
        
        {% endfor %}
    </div>

{% endif %}

{% endblock %}

todolist/templates/task_list2.html
{% extends 'main.html' %}

{% block content %}
{% if current_user.is_authenticated %}
<div class="header-bar">
        <div>
            <h1>"{{current_user.first_name|title}}" 님의 이번 달의 할 일<p>{{ random_quote }}</h1>
            <h3 style="margin:0">오늘 해야 할 일이 <i>{{ count }}</i>가지 남았어요!
               
            </h3>
        </div>

        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
        <a href="#">Login</a>
        {% endif %}
    </div>

    <div id="search-add-wrapper">
        <form action="" method="post" style="margin-top: 20px; display: flex;">
            <input type="text" name="search-area" value="{{ search_input }}">
            <input class="button" type="submit" value="Search">
            
        </form>
        <div style="text-align: right;">
            <a id="add-link" href="{{ url_for('views.task_form') }}" style="margin-right: 50px;" >&#x2b; 할일 추가</a>
            <a id="add-link1" href="{{ url_for('views.task_form') }}" style="margin-right: 100px;" >&#x2b;일기 쓰기</a>
       </div>
        
    </div>


    <div class="task-items-wrapper">
        {% for task in tasks %}
            <div class="task-wrapper">
                {% if task.complete %}
                    <div class="task-title">
                        <div class="task-complete-icon"></div>
                        <i><s><a href="{{ url_for('views.task_update', id=task.id) }}">{{task.title}}</a></s></i>
                    </div>
                <a class="delete-link" href="{{ url_for('views.task_delete', id=task.id) }}">&#215;</a>
                {% else %}
                    <div class="task-title">
                        <div class="task-incomplete-icon"></div>
                        <a href="{{ url_for('views.task_update', id=task.id) }}">{{task.title}}</a>
                    </div>
                <a class="delete-link" href="{{ url_for('views.task_delete', id=task.id) }}">&#215;</a>
                {% endif %}

            </div>
        {% else %}
        <h3 style="margin-left:10px;">해야 할 일이 없어요!</h3>
        
        {% endfor %}
    </div>

{% endif %}

{% endblock %}

todolist/templates/task_update.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{{ url_for('views.task_list') }}">&#8592; Back</a>
</div>

  <div class="card-body">
      <form action="" method="post">

          <label>Title</label>
          <input type="text" name="title" value="{{ task.title }}">

          <label>Description</label>
          <textarea rows="5" name="description">{{ task.description }}</textarea>

          <label>Complete<input type="checkbox" name="complete" checked></label>

          <input style="margin-top:10px;" class="button" type="submit" value="Submit">
      </form>
  </div>

{% endblock %}